### ISSUE TITLE
Меню в шапке

### ISSUE THREAD

**Issue by langovoi** [krddevdays/krddevdays.ru#51]
**Что есть:**
`Sidebar` с меню, который скрывается на узком разрешение.

**Что нужно:**
Меню в `NavBar`, которое отображается только на узком разрешение
(https://getbootstrap.com/docs/4.0/components/navbar/)

**Comment by binakot** [comment]
Возможно, это сюда.
На телефонах нет возможности открыть страницу событий.
Проверил на android и ios.

![](https://user-images.githubusercontent.com/1783893/53291700-78222000-37c8-11e9-9929-b44e5d72ea4a.png)

![](https://user-images.githubusercontent.com/1783893/53291705-9556ee80-37c8-11e9-822e-c284cebac32c.png)

**Comment by langovoi** [comment]
Ну потому что нет меню на мобилке, для этого эта задача и создана.
