### ISSUE TITLE
Инкапсулировать работу с TimePad API

### ISSUE THREAD

**Issue by langovoi** [krddevdays/krddevdays.ru#53]
**Что есть:**
Файлы `api.ts` и `server.ts`, которые в связки позволяют общаться с API TimePad.

**Что нужно:**
Искапсулировать работу с TimePad API на клиенте.

Клиент должен обращаться к своему сервер и получать ответ, а не работать с API TimePad, отслеживать его ошибки, конвертировать данные и т.п..

**Comment by EugeneButusov** [comment]
Зависит от #59, верно?

**Comment by langovoi** [comment]
Связано, да, но #59 не сейчас будет делаться
