### ISSUE TITLE
Фильтрация

### ISSUE THREAD

**Issue by jeetiss** [krddevdays/krddevdays.ru#63]
сейчас фильтры сделаны так что фетч данных важнее пользовательского ввода, а хочется чтоб было наоборот

![пример](https://ucarecdn.com/e76bc145-33c0-4a4e-b429-a0ae1daa2824/)

**Comment by langovoi** [comment]
**Что есть:**
Запрос данных и фильтрация делается в `getInitialProps`, из-за чего при смене фильтров идет запрос данных.

**Что нужно:**
Вынести фильтрацию только на клиент, но не сломать работу ссылок-фильтров.

**Comment by DenisLebedinsky** [comment]
Я сделаю

**Comment by neonick** [comment]
А зачем в этом фильтре состояние AND? Типа зачем мне выбрать Conf+Frontend, например? 

И еще, может в списке Conf поставить последним?

Цветовое кодирование кнопок? Фронт — красный, бек — зелёный... 

Что скажешь, @langovoi?

**Comment by langovoi** [comment]
> Цветовое кодирование кнопок? Фронт — красный, бек — зелёный...

Я бы не стал сейчас это делать, скоро у нас будет нормальный дизайн

> И еще, может в списке Conf поставить последним?

@binakot считает что как сейчас - правильно.

> А зачем в этом фильтре состояние AND? Типа зачем мне выбрать Conf+Frontend, например?

Мне кажется такой фильтр может быть полезен
