### ISSUE TITLE
Наполнить главную

### ISSUE THREAD

**Issue by langovoi** [krddevdays/krddevdays.ru#65]
_Originally posted by @neonick in https://github.com/krddevdays/krddevdays.ru/issues/54#issuecomment-467488855_

Нужно наполнить главную по аналогии с https://vk.com/@krddevdays-about

**Comment by neonick** [comment]
Возьму

**Comment by langovoi** [comment]
Вот еще можно взять текст из шаблона писем:
> Вся коммуникация в сообществе происходит через Telegram.
> 
> Если ты хотите задать вопрос организаторам, пообщаться с коллегами или поделиться опытом, у нас есть общий чат [@krddevdays_chat](t.me/krddevdays_chat) и следующие чаты по интересам:
> - [@krdfrontend](t.me/krdfrontend) для frontend-разработчиков;
> - [@krdbackend](t.me/krdbackend) для backend-разработчиков;
> - [@pythonkrd](t.me/pythonkrd) для python-разработчиков;
> - [@krdQA](t.me/krdQA) для QA-инженеров;
> - [@golangkrasnodar](t.me/golangkrasnodar) для Go-разработчиков;
> - [@rubykrd](t.me/rubykrd) для Ruby-разработчиков.
> 
> Основное правило – ни в одном из чатов выше нельзя публиковать вакансии и резюме, для этого есть [@krddevcareer](t.me/krddevcareer).
> 
> Подключайтесь, общайтесь и приходите на наши мероприятия.
